---
# yaml-language-server: $schema=https://screenkit.dev/schemas/episode.json

# The episode title. When there are no linebreaks, they will be inferred based
# on the approximate text width.
title: "CONFIGURING DEFAULT VALUES"

# The background music to be played during the episode.
# When not set, the backtrack will be defined by using the project's
# `backtrack_dir` configuration, and a track will be randomly selected.
# To disable the backtrack entirely, use `backtrack: false`.
# backtrack: resources/backtrack.mp3

# Define episode-specific scene configurations.
# When present, this will have higher precedence over the project's
# configuration, so you can have different intro/outro for each episode.
# scenes:
#   intro:
#     # The duration of the intro scene in seconds.
#     duration: 5.5
#
#     # The fade-in duration in seconds.
#     fade_in: 0
#
#     # The fade-out duration in seconds.
#     fade_out: 0.5
#
#     # The background color/image of the intro scene.
#     background: "#100f50"
#
#     # The title text to be displayed in the intro scene.
#     title:
#       x: 100
#       y: 300
#       font_path: open-sans/OpenSans-ExtraBold.ttf
#       size: 144
#       color: "#ffffff"
#
#     # The logo to be displayed in the video intro.
#     # Works best with a transparent PNG file in high resolution (at least 2x the
#     # size it'll be displayed).
#     logo:
#       path: images/logo.png
#       x: 100
#       y: 200
#       width: 200
#       height: 34
#
#     # The sound to be played along with the logo in the intro.
#     # This must correspond to a sound file in the sounds directory, with any
#     # audio extension (e.g. mp3, m4a, wav).
#     sound: sounds/chime.mp3
#
#   outro:
#     # The duration of the outro scene in seconds.
#     duration: 3.5
#
#     # The fade-in duration in seconds.
#     fade_in: 0.5
#
#     # The fade-out duration in seconds.
#     fade_out: 0.5
#
#     # The background color/image of the outro scene.
#     background: "#100f50"
#
#     # The sound to be played along with the logo in the outro.
#     sound: sounds/chime.mp3
#
#     # The logo to be displayed in the video outro.
#     logo:
#       path: images/logo.png
#       x: center
#       y: center
#       width: 500
#
#   segment:
#     # The duration of the crossover transition between segments in seconds.
#     crossfade_duration: 0.5

# Define episode-specific voice configuration.
# When present, this will have higher precedence over the project's
# configuration, so you can have different intro/outro segments for each
# episode.
# tts:
#   engine: elevenlabs
#   voice_id: 56AoDkrOh6qfVPDXZ7Pt
#   language_code: en
#   voice_settings:
#     speed: 0.9
#     stability: 0.5
#     similarity: 0.75
#     style: 0.0
